source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'UILoadControl_Example' do
  pod "UILoadControl", :path => "../"

  target 'UILoadControl_Tests' do
    inherit! :search_paths
  end
end