source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UILoadControl_Example', :exclusive => true do
  pod "UILoadControl", :path => "../"
end

target 'UILoadControl_Tests', :exclusive => true do
  pod "UILoadControl", :path => "../"
end
